# This file is automatically managed by <https://github.com/dtinth/jslibdevkit>.
# Any manual changes to this file may be overwritten.

npm:
  # Publishing to npm will be done by GitHub Actions — see `.github/workflows/publish.yml`.
  publish: false

github:
  release: true

plugins:
  '@spacet.me/news-fragments': {}
