#!/bin/bash -e

# This file is automatically managed by <https://github.com/dtinth/jslibdevkit>.
# Any manual changes to this file may be overwritten.

for I in temp/api/*.json; do
  # A weird issue with API Extractor adds `_2` suffix to some function names.
  # https://github.com/microsoft/rushstack/issues/2895
  sed -i.bak 's/_2//g' "$I"
done

cp temp/api/*.json dist/
