#!/bin/bash -e

# This file is automatically managed by <https://github.com/dtinth/jslibdevkit>.
# Any manual changes to this file may be overwritten.

changeset status
changeset version
version=$(jq -r '.version' package.json)
echo "Version to release: $version"
git add --update
git commit -am "v$version"
git tag -a "v$version" -m "v$version"
echo "Committed and tagged. Run 'git push --follow-tags' to push to remote."