# This file is automatically managed by <https://github.com/dtinth/repolicy>.
# Any manual changes to this file may be overwritten.

name: Publish
on:
  push:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@10693b3829bf86eb2572aef5f3571dcf5ca9287d # v2.2.2
        with:
          version: 7.13.1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm
      - name: Install dependencies and build
        run: pnpm install --prefer-offline
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@2a025e8ab1cfa4312c2868cb6aa3cd3b473b84bf # v1.3.0
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
